@REM Backup script generated by Areca v8.2.1 on 01.05.2025 14:46

@chcp 1252
@REM Incremental backup
@REM Target Group : "Windows"
@"D:/bin/Areca8/areca_cl.bat" backup -c -wdir "%LOCALAPPDATA%\Temp\tmp-stian" -config "%USERPROFILE%\.areca\workspace\Windows"

