@REM Backup script generated by Areca v8.2.6 on 23.08.2026 12:46

@chcp 1252
@REM Incremental backup
@REM Target Group : "Windows"
@"D:/bin/Areca8/areca_cl.bat" backup -c -wdir "C:\Users\Stian\AppData\Local\Temp\tmp-stian" -config "C:/Users/Stian/.areca/workspace/Windows"

