@REM Backup script generated by Areca v7.5 on Jul 15, 2022 9:31 AM

@chcp 1252
@REM Incremental backup
@REM Target Group : "Windows"
@"D:/bin/Areca/areca_cl.exe" backup -c -wdir "C:\Users\Stian\AppData\Local\Temp\tmp-stian" -config "C:/Users/Stian/.areca/workspace/Windows"

