DISM.exe /Online /Disable-Feature /featurename:Client-DeviceLockdown /Remove
DISM.exe /Online /Disable-Feature /featurename:Client-EmbeddedBootExp /Remove
DISM.exe /Online /Disable-Feature /featurename:Client-EmbeddedLogon /Remove
DISM.exe /Online /Disable-Feature /featurename:Client-EmbeddedShellLauncher /Remove
DISM.exe /Online /Disable-Feature /featurename:Client-KeyboardFilter /Remove
DISM.exe /Online /Disable-Feature /featurename:Client-UnifiedWriteFilter /Remove
DISM.exe /Online /Disable-Feature /featurename:ClientForNFS-Infrastructure /Remove
DISM.exe /Online /Disable-Feature /featurename:Containers /Remove
DISM.exe /Online /Disable-Feature /featurename:DataCenterBridging /Remove
DISM.exe /Online /Disable-Feature /featurename:DirectPlay /Remove
DISM.exe /Online /Disable-Feature /featurename:DirectoryServices-ADAM-Client /Remove
DISM.exe /Online /Disable-Feature /featurename:FaxServicesClientPackage /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ASP /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ASPNET /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ASPNET45 /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ApplicationDevelopment /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ApplicationInit /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-BasicAuthentication /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-CGI /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-CertProvider /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ClientCertificateMappingAuthentication /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-CommonHttpFeatures /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-CustomLogging /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-DefaultDocument /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-DigestAuthentication /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-DirectoryBrowsing /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-FTPExtensibility /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-FTPServer /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-FTPSvc /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-HealthAndDiagnostics /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-HostableWebCore /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpCompressionDynamic /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpCompressionStatic /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpErrors /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpLogging /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpRedirect /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-HttpTracing /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-IIS6ManagementCompatibility /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-IISCertificateMappingAuthentication /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-IPSecurity /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ISAPIExtensions /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ISAPIFilter /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-LegacyScripts /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-LegacySnapIn /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-LoggingLibraries /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ManagementConsole /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ManagementScriptingTools /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ManagementService /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-Metabase /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-NetFxExtensibility /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-NetFxExtensibility45 /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ODBCLogging /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-Performance /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-RequestFiltering /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-RequestMonitor /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-Security /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-ServerSideIncludes /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-StaticContent /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-URLAuthorization /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-WMICompatibility /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-WebDAV /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-WebServer /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-WebServerManagementTools /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-WebServerRole /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-WebSockets /Remove
DISM.exe /Online /Disable-Feature /featurename:IIS-WindowsAuthentication /Remove
DISM.exe /Online /Disable-Feature /featurename:Internet-Explorer-Optional-amd64 /Remove
DISM.exe /Online /Disable-Feature /featurename:IsolatedUserMode /Remove
DISM.exe /Online /Disable-Feature /featurename:LegacyComponents /Remove
DISM.exe /Online /Disable-Feature /featurename:MSMQ-ADIntegration /Remove
DISM.exe /Online /Disable-Feature /featurename:MSMQ-Container /Remove
DISM.exe /Online /Disable-Feature /featurename:MSMQ-DCOMProxy /Remove
DISM.exe /Online /Disable-Feature /featurename:MSMQ-HTTP /Remove
DISM.exe /Online /Disable-Feature /featurename:MSMQ-Multicast /Remove
DISM.exe /Online /Disable-Feature /featurename:MSMQ-Server /Remove
DISM.exe /Online /Disable-Feature /featurename:MSMQ-Triggers /Remove
DISM.exe /Online /Disable-Feature /featurename:MSRDC-Infrastructure /Remove
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V /Remove
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-All /Remove
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-Hypervisor /Remove
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-Management-Clients /Remove
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-Management-PowerShell /Remove
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-Services /Remove
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Hyper-V-Tools-All /Remove
DISM.exe /Online /Disable-Feature /featurename:Microsoft-Windows-Subsystem-Linux /Remove
DISM.exe /Online /Disable-Feature /featurename:MultiPoint-Connector /Remove
DISM.exe /Online /Disable-Feature /featurename:MultiPoint-Connector-Services /Remove
DISM.exe /Online /Disable-Feature /featurename:MultiPoint-Tools /Remove
DISM.exe /Online /Disable-Feature /featurename:NFS-Administration /Remove
DISM.exe /Online /Disable-Feature /featurename:Printing-Foundation-Features /Remove
DISM.exe /Online /Disable-Feature /featurename:Printing-Foundation-InternetPrinting-Client /Remove
DISM.exe /Online /Disable-Feature /featurename:Printing-Foundation-LPDPrintService /Remove
DISM.exe /Online /Disable-Feature /featurename:Printing-Foundation-LPRPortMonitor /Remove
DISM.exe /Online /Disable-Feature /featurename:Printing-PrintToPDFServices-Features /Remove
DISM.exe /Online /Disable-Feature /featurename:Printing-XPSServices-Features /Remove
DISM.exe /Online /Disable-Feature /featurename:RasCMAK /Remove
DISM.exe /Online /Disable-Feature /featurename:RasRip /Remove
DISM.exe /Online /Disable-Feature /featurename:SMB1Protocol /Remove
DISM.exe /Online /Disable-Feature /featurename:SNMP /Remove
DISM.exe /Online /Disable-Feature /featurename:ScanManagementConsole /Remove
DISM.exe /Online /Disable-Feature /featurename:ServicesForNFS-ClientOnly /Remove
DISM.exe /Online /Disable-Feature /featurename:SimpleTCP /Remove
DISM.exe /Online /Disable-Feature /featurename:SmbDirect /Remove
DISM.exe /Online /Disable-Feature /featurename:TFTP /Remove
DISM.exe /Online /Disable-Feature /featurename:TIFFIFilter /Remove
DISM.exe /Online /Disable-Feature /featurename:TelnetClient /Remove
DISM.exe /Online /Disable-Feature /featurename:WAS-ConfigurationAPI /Remove
DISM.exe /Online /Disable-Feature /featurename:WAS-NetFxEnvironment /Remove
DISM.exe /Online /Disable-Feature /featurename:WAS-ProcessModel /Remove
DISM.exe /Online /Disable-Feature /featurename:WAS-WindowsActivationService /Remove
DISM.exe /Online /Disable-Feature /featurename:WCF-HTTP-Activation /Remove
DISM.exe /Online /Disable-Feature /featurename:WCF-HTTP-Activation45 /Remove
DISM.exe /Online /Disable-Feature /featurename:WCF-MSMQ-Activation45 /Remove
DISM.exe /Online /Disable-Feature /featurename:WCF-NonHTTP-Activation /Remove
DISM.exe /Online /Disable-Feature /featurename:WCF-Pipe-Activation45 /Remove
DISM.exe /Online /Disable-Feature /featurename:WCF-Services45 /Remove
DISM.exe /Online /Disable-Feature /featurename:WCF-TCP-Activation45 /Remove
DISM.exe /Online /Disable-Feature /featurename:WCF-TCP-PortSharing45 /Remove
DISM.exe /Online /Disable-Feature /featurename:WMISnmpProvider /Remove
DISM.exe /Online /Disable-Feature /featurename:Windows-Identity-Foundation /Remove
DISM.exe /Online /Disable-Feature /featurename:WorkFolders-Client /Remove
DISM.exe /Online /Disable-Feature /featurename:Xps-Foundation-Xps-Viewer /Remove
DISM.exe /Online /Disable-Feature /featurename:Xps-Foundation-Xps-Viewer /Remove
